### PR TITLE
figure added

### PR DESCRIPTION
**Pull request by manpreet9112**

### CODE REVIEW

**Comment by manpreet9112** [comment]
Because \ref and labels of equations should be meaningful. But in this file, number(as 12.1)  were written instead of meaningful name of label. So, I remove this. And sir said that after adding figure sent PR. 
 I will send you next PR for proper \ref name and \label.

**Comment by mandeeps708** [comment]
Why you changed it to 12.x? Will it be dynamic with the chapter name? IIRC, the eq. no. changed automatically before? Also see the your changes, here: https://github.com/GreatDevelopers/DesignAids/pull/5/files 

I am closing this for now. Waiting for your next PR!

**Comment by manpreet9112** [comment]
By mistake, It should be proper name of equation so that  anyone can understand. No, we have to specify it manually. And  What is IIRC?

**Comment by mandeeps708** [comment]
Do you mean now you are going to add \ref to equations?
And for IIRC, see: http://bfy.tw/MA5

**Pull request closed without merging**
